// <auto-generated />
namespace CareerVisa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CareerVisa_CareerField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CareerVisa_CareerField));
        
        string IMigrationMetadata.Id
        {
            get { return "201612240208032_CareerVisa_CareerField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
